# Generated by Django 5.0.1 on 2024-01-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_amount_paid_order_payment_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
