# Generated by Django 5.0.1 on 2024-01-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='has_logo',
        ),
    ]
