# Generated by Django 5.0.1 on 2024-01-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
