# Generated by Django 5.0.1 on 2024-01-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Đã cọc', 'Đã cọc'), ('Đã sản xuất', 'Đã sản xuất'), ('Đã giao', 'Đã giao'), ('Đã hủy', 'Đã hủy')], default='Đang xử lý', max_length=20),
        ),
    ]
