# Generated by Django 5.0.1 on 2024-01-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_order_completeed_date_order_delivered_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_paid',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='unpaid',
            field=models.FloatField(default=0),
        ),
    ]
