# Generated by Django 5.0.1 on 2024-01-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_amount_paid_order_paid_order_unpaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completeed_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='neck',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='collar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bo cổ/tay'),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành'),
        ),
        migrations.AddField(
            model_name='order',
            name='pillar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trụ áo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='material',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Lụa', 'Lụa'), ('Kaki', 'Kaki'), ('Jeans', 'Jeans'), ('Lanh', 'Lanh'), ('Thun', 'Thun'), ('Nỉ', 'Nỉ'), ('Vải dù', 'Vải dù'), ('Vải mưa', 'Vải mưa')], default='Cotton', max_length=50, verbose_name='Chất liệu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='style',
            field=models.CharField(choices=[('Cổ bẻ', 'Cổ bẻ'), ('Cổ trụ', 'Cổ trụ'), ('Cổ tim', 'Cổ tim'), ('Cổ tròn', 'Cổ tròn'), ('Cổ V', 'Cổ V'), ('Cổ chữ U', 'Cổ chữ U'), ('Cổ sơ mi', 'Cổ sơ mi'), ('Cổ đức', 'Cổ đức')], default='Cổ bẻ', max_length=50, verbose_name='Kiểu dáng'),
        ),
    ]
