# Generated by Django 5.0.1 on 2024-01-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_order_completeed_date_remove_order_hand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày dự kiến'),
        ),
    ]
