# Generated by Django 5.0.1 on 2024-01-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_order_expected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
