# Generated by Django 5.0.1 on 2024-01-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_order_all_unit_price_order_vat_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='all_unit_price',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_vat',
            field=models.FloatField(default=0, verbose_name='Thành tiền'),
        ),
    ]
