# Generated by Django 5.0.1 on 2024-01-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_order_all_unit_price_order_total_price_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.FloatField(default=0.08, verbose_name='VAT'),
        ),
    ]
